### ISSUE TITLE
Joe's code+product lines

### ISSUE THREAD

**Issue by Ginfung** [ai-se/SPL#2]
I merged my product lines parser into joe's code so that it can be applied to Joe's GALE.
Since galeMutate was for continuous space, I wrote any other galeMutate for product lines (at this time the algorithm is the same as my own version before).
OK. Here are some notes:
1) I found that my GALE is exactly the same as joe's (even though jmoo looks more complex). 
2)  Both of our GALEs get the same result. such as for the fonseca model,
![figure01_fonseca_](https://cloud.githubusercontent.com/assets/3222148/10770942/5e51305c-7cc4-11e5-9cb8-e37f9b57bb50.png)
see the red points, the frontier, hyper-volume are worse than the green/blue sets.
Of course, the # of evaluations is much less for GALE.
3) If the upper result is acceptable, the mutation for product line is unacceptable at this time.
in the small model, almost all generation can get effective mutation,
in the large model(eshop), about 14.2% generation can get effective mutation.
Among the generation containing effective mutation, the pass rate is (unit:%)
```
rank ,         name ,    med   ,  iqr
----------------------------------------------------
   1 ,        eshop ,    16.67  ,  14.75  (--*            |              ), 8.33,  16.67,  23.08
   2 ,   cell phone ,    100.00  ,  16.67 (               |        -----*), 83.33,  100.00,  100.00
```

**Comment by timm** [comment]
>  I found that my GALE is exactly the same as joe's (even though jmoo looks more complex). 

hooray! of course your code is simpler.... for now. wait for 3 years from now when next student comes along complaining about @Ginfung 's too complex code!

> in the large model(eshop), about 14.2% generation can get effective mutation.

and does it get worse for models more complex than eshop? i hope so!

now, you have a baseline, a problem worth reporting. so.... can you use the leaves generated by GALE to better control new products? (delete branches not found in GALE's mutated set, delete branches that do not have ranges always found in GALE's clusters, etc, rearrange subtrees favoring branches with ranges found more often in best end of GALE's mutated set, etc). 

and if you are successful, you will see results larger than your baseline of 14.2%

**Comment by Ginfung** [comment]
Although the baseline is “appalling" at this time, I have it at least! Thanks for your guide @timm  !
For the larger model, I remembered that there is only one model(https://github.com/ai-se/SPL/blob/master/feature_tree_data/EIS.xml) which is larger than the eshop in SPLOT. Do you know other repos(instances) which contains thousands of features?! Looking for challenging the algorithm (SPLOT was crashed down again). @timm

**Comment by timm** [comment]
look for the linux variability project. used by abdel in our ase 2013 paper, which u should have read already. 300,000+ constraints. https://goo.gl/rqF4JH
