### ISSUE TITLE
11-05-15

### ISSUE THREAD

**Issue by Ginfung** [ai-se/SPL#6]
```
done:
1. change dist for spl candidates
2. parser for LAVT
3. mutate engine

doing:
1. stat for leaves cluster
2. merge LAVT to FTModel

todo:
1. track mutate tree-> avoid early stop
2. mutate from objectives

```

**Comment by timm** [comment]
looking forward to simple baselines:

- [ ] RX1: generate large N number of products (using your top down method, i think) then cull N using WHERE with east-west pruning
- [ ] RX2: using GALE to find products 
- [ ] RX3,4,5: using DE, NSGA-III, MOEA/D to find products

**Comment by Ginfung** [comment]
- [ ]  A tutorial on the performance assessment of stochastic mult-iobjective optimizers 

http://www.tik.ee.ethz.ch/sop/pisa/publications/emo-tutorial-2up.pdf
